config/routes.rb
Rails.application.routes.draw do
  resources :public_accounts

  mount WeixinRailsMiddleware::Engine, at: "/"

  root 'public_accounts#index'

end

app/models/public_account.rb
class PublicAccount < ActiveRecord::Base
  # It will auto generate weixin token and secret
  include WeixinRailsMiddleware::AutoGenerateWeixinTokenSecretKey
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/public_accounts_controller.rb
class PublicAccountsController < ApplicationController
  before_action :set_public_account, only: [:show, :edit, :update, :destroy]

  # GET /public_accounts
  # GET /public_accounts.json
  def index
    @public_accounts = PublicAccount.all
  end

  # GET /public_accounts/1
  # GET /public_accounts/1.json
  def show
  end

  # GET /public_accounts/new
  def new
    @public_account = PublicAccount.new
  end

  # GET /public_accounts/1/edit
  def edit
  end

  # POST /public_accounts
  # POST /public_accounts.json
  def create
    @public_account = PublicAccount.new(public_account_params)

    respond_to do |format|
      if @public_account.save
        format.html { redirect_to @public_account, notice: 'Public account was successfully created.' }
        format.json { render :show, status: :created, location: @public_account }
      else
        format.html { render :new }
        format.json { render json: @public_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /public_accounts/1
  # PATCH/PUT /public_accounts/1.json
  def update
    respond_to do |format|
      if @public_account.update(public_account_params)
        format.html { redirect_to @public_account, notice: 'Public account was successfully updated.' }
        format.json { render :show, status: :ok, location: @public_account }
      else
        format.html { render :edit }
        format.json { render json: @public_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /public_accounts/1
  # DELETE /public_accounts/1.json
  def destroy
    @public_account.destroy
    respond_to do |format|
      format.html { redirect_to public_accounts_url, notice: 'Public account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_public_account
      @public_account = PublicAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def public_account_params
      params.require(:public_account).permit(:name)
    end
end

app/controllers/wechat_controller.rb
class WechatController < ApplicationController
  def index
    if params['echostr']
      p params['echostr']
    else
      p 'hello, This is richard-ma-1985'
    end
  end

  wechat_responder

  on :text do |request, content|
    request.reply.text "echo: #{content}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_accounts_helper.rb
module PublicAccountsHelper
end

app/helpers/wechat_helper.rb
module WechatHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RichardMa1985</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/public_accounts/_form.html.erb
<%= form_for(@public_account) do |f| %>
  <% if @public_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@public_account.errors.count, "error") %> prohibited this public_account from being saved:</h2>

      <ul>
      <% @public_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/public_accounts/edit.html.erb
<h1>Editing public_account</h1>

<%= render 'form' %>

<%= link_to 'Show', @public_account %> |
<%= link_to 'Back', public_accounts_path %>

app/views/public_accounts/index.html.erb
<h1>Listing public_accounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @public_accounts.each do |public_account| %>
      <tr>
        <td><%= public_account.name %></td>
        <td><%= weixin_engine.weixin_server_url(public_account.weixin_secret_key) %></td>
        <td><%= public_account.weixin_token %></td>
        <td><%= link_to 'Show', public_account %></td>
        <td><%= link_to 'Edit', edit_public_account_path(public_account) %></td>
        <td><%= link_to 'Destroy', public_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Public account', new_public_account_path %>

app/views/public_accounts/new.html.erb
<h1>New public_account</h1>

<%= render 'form' %>

<%= link_to 'Back', public_accounts_path %>

app/views/public_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @public_account.name %>
</p>

<%= link_to 'Edit', edit_public_account_path(@public_account) %> |
<%= link_to 'Back', public_accounts_path %>